const BASE = "/case-studies/101-reporters";

export const reportersImages = {
  clientLogo: { src: `${BASE}/client-logo.png`, width: 360, height: 120 },
  secondaryResearch: { src: `${BASE}/secondary-research.png`, width: 2376, height: 850 },
  stakeholder1: { src: `${BASE}/stakeholder-1.png`, width: 300, height: 300 },
  stakeholder2: { src: `${BASE}/stakeholder-2.png`, width: 300, height: 300 },
  stakeholder3: { src: `${BASE}/stakeholder-3.png`, width: 300, height: 300 },
  potentialUsers: { src: `${BASE}/potential-users.png`, width: 1542, height: 610 },
  userGroups: { src: `${BASE}/user-groups.png`, width: 1576, height: 1376 },
  empathyMap: { src: `${BASE}/empathy-map.png`, width: 1108, height: 1107 },
  persona1: { src: `${BASE}/persona-1.png`, width: 1275, height: 798 },
  persona2: { src: `${BASE}/persona-2.png`, width: 1275, height: 798 },
  problemStatement: { src: `${BASE}/problem-statement.png`, width: 3138, height: 819 },
  hypothesisStatement: { src: `${BASE}/hypothesis-statement.png`, width: 3138, height: 819 },
  brainstorming: { src: `${BASE}/brainstorming.png`, width: 801, height: 555 },
  ia: { src: `${BASE}/ia.png`, width: 1008, height: 574 },
  userFlow: { src: `${BASE}/user-flow.png`, width: 1433, height: 1012 },
  lofi: { src: `${BASE}/lofi.png`, width: 2033, height: 1008 },
  hifi: { src: `${BASE}/hifi.png`, width: 2005, height: 870 },
  visualDesign: { src: `${BASE}/visual-design.png`, width: 1512, height: 2894 },
  uiDesign: { src: `${BASE}/ui-design.png`, width: 2852, height: 1674 },
  gallery1: { src: `${BASE}/gallery-1.png`, width: 1030, height: 1030 },
  gallery2: { src: `${BASE}/gallery-2.png`, width: 1030, height: 1030 },
  gallery3: { src: `${BASE}/gallery-3.png`, width: 1030, height: 1031 },
  gallery4: { src: `${BASE}/gallery-4.png`, width: 1030, height: 871 },
  gallery5: { src: `${BASE}/gallery-5.png`, width: 917, height: 687 },
  prototypeVideo: `${BASE}/videos/prototype.mp4`,
};
