/**
 * GENERATED by scripts/prerender-voice.mjs. Do not edit.
 *
 * Maps a fixed line to its pre-rendered Eleven v3 audio. A miss is not an
 * error: the line is synthesised live on Flash instead, which is the same words
 * in a slightly plainer delivery.
 *
 * Empty until the opener copy is settled and the script is run. Shipping this
 * file empty is deliberate — the runtime lookup is live from the start, so
 * nothing has to change in the client when the audio lands.
 */
export const PRERENDERED: Record<string, string> = {};
