/**
 * GENERATED by scripts/prerender-voice.mjs. Do not edit.
 *
 * Maps a fixed line to its pre-rendered eleven_v3 audio. A miss is not an error:
 * the line is synthesised live on Flash instead, which is the same words in a
 * slightly plainer delivery.
 */
export const PRERENDERED: Record<string, string> = {
  "Hi, I'm Lorem. How are you doing today? Hold Space when you want to talk.": "/voice/greet-new-desktop.mp3",
  "Hi, I'm Lorem. How are you doing today? Tap the orb when you want to talk.": "/voice/greet-new-touch.mp3",
  "Welcome back. How are you doing today? Hold Space when you want to talk.": "/voice/greet-back-desktop.mp3",
  "Welcome back. How are you doing today? Tap the orb when you want to talk.": "/voice/greet-back-touch.mp3"
};
