const BASE = "/case-studies/uniquefit";

export const uniquefitImages = {
  clientLogo: { src: `${BASE}/client-logo.png`, width: 320, height: 120 },
  userReview: { src: `${BASE}/user-review.png`, width: 2818, height: 1176 },
  ecommerceProblem: { src: `${BASE}/ecommerce-problem.png`, width: 2091, height: 450 },
  surveyData: { src: `${BASE}/survey-data.png`, width: 5142, height: 3862 },
  interviewData: { src: `${BASE}/interview-data.png`, width: 5184, height: 2132 },
  competitorAudit: { src: `${BASE}/competitor-audit.png`, width: 1419, height: 544 },
  empathyMap: { src: `${BASE}/empathy-map.png`, width: 1696, height: 1696 },
  persona1: { src: `${BASE}/persona-1.png`, width: 1829, height: 1482 },
  persona2: { src: `${BASE}/persona-2.png`, width: 1829, height: 1569 },
  journeyMap: { src: `${BASE}/journey-map.png`, width: 1601, height: 850 },
  problemStatement: { src: `${BASE}/problem-statement.png`, width: 2092, height: 648 },
  hypothesisStatement: { src: `${BASE}/hypothesis-statement.png`, width: 2092, height: 654 },
  uvp: { src: `${BASE}/uvp.png`, width: 2092, height: 546 },
  crazy8s: { src: `${BASE}/crazy-8s.png`, width: 1181, height: 830 },
  taskFlow: { src: `${BASE}/task-flow.png`, width: 2756, height: 1239 },
  userFlow: { src: `${BASE}/user-flow.png`, width: 2583, height: 5165 },
  ia: { src: `${BASE}/ia.png`, width: 1500, height: 1745 },
  lofiMobile: { src: `${BASE}/lofi-mobile.png`, width: 943, height: 679 },
  lofiWeb: { src: `${BASE}/lofi-web.png`, width: 1918, height: 836 },
  hifiMobile: { src: `${BASE}/hifi-mobile.png`, width: 1805, height: 1926 },
  hifiWeb: { src: `${BASE}/hifi-web.png`, width: 2475, height: 1171 },
  customDashboardWireframe: { src: `${BASE}/custom-dashboard-wireframe.png`, width: 1440, height: 680 },
  customVariants: { src: `${BASE}/custom-variants.png`, width: 3600, height: 1319 },
  visualSystem: { src: `${BASE}/visual-system.png`, width: 2880, height: 10888 },
  customUiMobile: { src: `${BASE}/custom-ui-mobile.png`, width: 3600, height: 1319 },
  usabilityHeatmap: { src: `${BASE}/usability-heatmap.png`, width: 5059, height: 3739 },
  revisions: { src: `${BASE}/revisions.png`, width: 2880, height: 1862 },
  devHandoff: { src: `${BASE}/dev-handoff.png`, width: 2880, height: 2662 },
} as const;
